## **TF-IDF dan Word Embeding**

**TF-IDF**

In [ ]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [ ]:
import pandas as pd
import ast
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
from google.colab import drive
import pandas as pd

# Mount Google Drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Baca CSV dari path Drive
df = pd.read_csv('/content/drive/MyDrive/Semester 7/PPW/hasil_preprocessing_berita.csv')
df.head()

,Teks Asli,Setelah Stopword Removal,Setelah Cleaning,Setelah Normalisasi,Setelah Stemming,Tokenisasi Akhir
0,alfamart kembali menggelar aksi donor darah se...,"['alfamart', 'kembali', 'menggelar', 'aksi', '...","['alfamart', 'kembali', 'menggelar', 'aksi', '...","['alfamart', 'kembali', 'menggelar', 'aksi', '...","['alfamart', 'kembali', 'gelar', 'aksi', 'dono...","['alfamart', 'kembali', 'gelar', 'aksi', 'dono..."
1,"menteri koordinator bidang hukum, ham, imigras...","['menteri', 'koordinator', 'bidang', 'hukum,',...","['menteri', 'koordinator', 'bidang', 'hukum', ...","['menteri', 'koordinator', 'bidang', 'hukum', ...","['menteri', 'koordinator', 'bidang', 'hukum', ...","['menteri', 'koordinator', 'bidang', 'hukum', ..."
2,gubernur sumatera utara (sumut) bobby nasution...,"['gubernur', 'sumatera', 'utara', '(sumut)', '...","['gubernur', 'sumatera', 'utara', 'sumut', 'bo...","['gubernur', 'sumatera', 'utara', 'sumut', 'bo...","['gubernur', 'sumatera', 'utara', 'sumut', 'bo...","['gubernur', 'sumatera', 'utara', 'sumut', 'bo..."
3,dukungan untuk plt ketua umum partai persatuan...,"['dukungan', 'plt', 'ketua', 'umum', 'partai',...","['dukungan', 'plt', 'ketua', 'umum', 'partai',...","['dukungan', 'plt', 'ketua', 'umum', 'partai',...","['dukung', 'plt', 'ketua', 'umum', 'partai', '...","['dukung', 'plt', 'ketua', 'umum', 'partai', '..."
4,bagi pengguna whoosh rute jakarta-bandung atau...,"['bagi', 'pengguna', 'whoosh', 'rute', 'jakart...","['bagi', 'pengguna', 'whoosh', 'rute', 'jakart...","['bagi', 'pengguna', 'whoosh', 'rute', 'jakart...","['bagi', 'guna', 'whoosh', 'rute', 'jakartaban...","['bagi', 'guna', 'whoosh', 'rute', 'jakartaban..."

In [ ]:
print(type(df["Tokenisasi Akhir"].iloc[0]))
print(df["Tokenisasi Akhir"].iloc[0])

<class 'str'>
['alfamart', 'kembali', 'gelar', 'aksi', 'donor', 'darah', 'serentak', 'kotakabupaten', 'lama', 'satu', 'minggu', 'september', 'dalam', 'program', 'sehat', 'tetes', 'darah', 'pertiwi', 'giat', 'sosial', 'ini', 'alfamart', 'target', 'kumpul', 'kantong', 'darah', 'bantu', 'penuh', 'stok', 'palang', 'merah', 'indonesia', 'pmi', 'ini', 'salah', 'satu', 'kontribusi', 'alfamart', 'bantu', 'pasien', 'butuh', 'transfusi', 'darah', 'gandeng', 'pmi', 'daerah', 'harap', 'ribu', 'kantong', 'darah', 'dapat', 'capai', 'salur', 'kepada', 'butuh', 'kata', 'corporate', 'affairs', 'director', 'alfamart', 'solihin', 'dalam', 'terang', 'tulis', 'rabu', 'scroll', 'continue', 'with', 'content', 'giat', 'donor', 'darah', 'kali', 'jadi', 'bagi', 'rangkai', 'semarak', 'ulang', 'tahun', 'alfamart', 'sua', 'ke', 'target', 'kantong', 'darah', 'pilih', 'bagai', 'refleksi', 'usia', 'alfamart', 'telah', 'tahun', 'layan', 'masyarakat', 'indonesia', 'solihin', 'tambah', 'donor', 'darah', 'telah', 'jadi', 'giat', 'rutin', 'alfamart', 'tahun', 'ini', 'program', 'dapat', 'dukung', 'jumlah', 'mitra', 'seperti', 'bear', 'brand', 'milo', 'aquviva', 'ichitan', 'paper', 'bag', 'program', 'jadi', 'bagi', 'tanggung', 'jawab', 'sosial', 'usaha', 'kumpul', 'darah', 'dalam', 'jumlah', 'besar', 'makin', 'banyak', 'pasien', 'bisa', 'bantu', 'ujar', 'solihin', 'selain', 'donor', 'darah', 'giat', 'turut', 'isi', 'talkshow', 'sehat', 'sama', 'direktur', 'rumah', 'sakit', 'islam', 'sari', 'asih', 'arrahmah', 'irhami', 'sempat', 'itu', 'irhami', 'tekan', 'penting', 'siap', 'belum', 'donor', 'darah', 'selain', 'pasti', 'kondisi', 'tubuh', 'sehat', 'calon', 'donor', 'perlu', 'jaga', 'pola', 'tidur', 'cukup', 'serta', 'pola', 'makan', 'atur', 'agar', 'proses', 'donor', 'darah', 'jalan', 'lancar', 'ujar', 'irhami', 'apresiasi', 'khusus', 'beri', 'lalu', 'blood', 'heroes', 'bagi', 'donor', 'telah', 'sumbang', 'darah', 'lebih', 'kali', 'harga', 'serah', 'langsung', 'oleh', 'solihin', 'sama', 'wakil', 'ketua', 'pmi', 'provinsi', 'banten', 'jaenudin', 'sementara', 'itu', 'jaenudin', 'sampai', 'apresiasi', 'hadap', 'program', 'donor', 'darah', 'jalan', 'alfamart', 'kumpul', 'kantong', 'darah', 'kumpul', 'lama', 'september', 'alfamart', 'dapat', 'jadi', 'contoh', 'bagi', 'usaha', 'lain', 'donor', 'darah', 'bukan', 'hanya', 'manfaat', 'bagi', 'sehat', 'tetapi', 'wujud', 'nyata', 'peduli', 'kepada', 'sama', 'ujar', 'jaenudin', 'kantong', 'darah', 'kumpul', 'akan', 'sangat', 'arti', 'bagi', 'hidup', 'orang', 'lain', 'gantung', 'kepada', 'stok', 'darah', 'pmi', 'sambung', 'para', 'serta', 'donor', 'darah', 'dapat', 'paket', 'makan', 'gizi', 'goodie', 'bag', 'bagai', 'tambah', 'nutrisi', 'seperti', 'susu', 'murni', 'bear', 'brand', 'susu', 'sapi', 'steril', 'murni', 'milo', 'biskuit', 'air', 'mineral', 'aquviva', 'telah', 'lalu', 'tahap', 'nano', 'purifikasi', 'pasti', 'murni', 'imbang', 'mineral', 'ichitan', 'serta', 'pelbagai', 'nutrisi', 'tambah', 'salah', 'orang', 'donor', 'baru', 'pertama', 'kali', 'laku', 'donor', 'darah', 'rico', 'aku', 'awal', 'sempat', 'takut', 'sedikit', 'takut', 'awal', 'jarum', 'tapi', 'rani', 'diri', 'harap', 'darah', 'bisa', 'manfaat', 'kata', 'rico', 'donor', 'lain', 'mas', 'justru', 'rutin', 'ikut', 'giat', 'ini', 'manfaat', 'rasa', 'langsung', 'apalagi', 'bantu', 'butuh', 'alfamart', 'konsisten', 'ada', 'ujar', 'mas', 'giat', 'donor', 'darah', 'alfamart', 'jadi', 'bagi', 'upaya', 'dukung', 'sedia', 'darah', 'pmi', 'sangat', 'butuh', 'pasien', 'masuk', 'idap', 'thalassemia', 'seperti', 'intan', 'turut', 'beri', 'cerita', 'acara', 'sebut', 'intan', 'harus', 'rutin', 'jalan', 'transfusi', 'darah', 'sejak', 'usia', 'tahun', 'bagi', 'intan', 'tiap', 'tetes', 'darah', 'sedia', 'pmi', 'topang', 'hidup', 'kalau', 'transfusi', 'badan', 'lemas', 'sekali', 'rasa', 'sanggup', 'diri', 'donor', 'darah', 'seperti', 'ini', 'bisa', 'tetap', 'lanjut', 'aktivitas', 'seharihari', 'tutur', 'intan', 'kisah', 'intan', 'jadi', 'bukti', 'nyata', 'bahwa', 'donor', 'darah', 'sekadar', 'angka', 'tetapi', 'tentang', 'harap', 'selamat', 'hidup']

In [ ]:
df["Tokenisasi Akhir_joined"] = df["Tokenisasi Akhir"].apply(
    lambda x: " ".join(ast.literal_eval(x)) if isinstance(x, str) else ""
)


df[["Tokenisasi Akhir", "Tokenisasi Akhir_joined"]].head()

,Tokenisasi Akhir,Tokenisasi Akhir_joined
0,"['alfamart', 'kembali', 'gelar', 'aksi', 'dono...",alfamart kembali gelar aksi donor darah serent...
1,"['menteri', 'koordinator', 'bidang', 'hukum', ...",menteri koordinator bidang hukum ham imigrasi ...
2,"['gubernur', 'sumatera', 'utara', 'sumut', 'bo...",gubernur sumatera utara sumut bobby nasution t...
3,"['dukung', 'plt', 'ketua', 'umum', 'partai', '...",dukung plt ketua umum partai satu bangun ppp m...
4,"['bagi', 'guna', 'whoosh', 'rute', 'jakartaban...",bagi guna whoosh rute jakartabandung atau bali...

In [ ]:
vectorizer = TfidfVectorizer(max_features=1000)  # ambil 1000 fitur teratas

X_tfidf = vectorizer.fit_transform(df["Tokenisasi Akhir_joined"])

tfidf_df = pd.DataFrame(
    X_tfidf.toarray(),
    columns=vectorizer.get_feature_names_out()
)

tfidf_df.head()

,acara,ada,adapun,adil,afp,afriansyah,agam,agama,agar,agenda,...,wira,with,wujud,xiii,ya,yaitu,yakin,yakni,yang,yayasan
0,0.016249,0.010689,0.0,0.0,0.0,0.0,0.0,0.0,0.013411,0.0,...,0.0,0.005929,0.018111,0.0,0.0,0.000000,0.00000,0.0,0.000000,0.0
1,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.012363,0.000000,0.0,0.0,0.000000,0.00000,0.0,0.035928,0.0
2,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.014949,0.000000,0.0,0.0,0.000000,0.00000,0.0,0.000000,0.0
3,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.033599,0.0,...,0.0,0.014854,0.000000,0.0,0.0,0.000000,0.04709,0.0,0.000000,0.0
4,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.029843,0.000000,0.0,0.0,0.079639,0.00000,0.0,0.000000,0.0

**Word Embedding**

In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
Collecting numpy<2.0,>=1.18.5 (from gensim)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.5 MB/s eta 0:00:00
Collecting scipy<1.14.0,>=1.7.0 (from gensim)
  Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 5.5 MB/s eta 0:00:00
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.3.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=1.8.1->gensim) (1.17.3)
Downloading gensim-4.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.6/26.6 MB 71.2 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 103.0 MB/s eta 0:00:00
Downloading scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 17.3 MB/s eta 0:00:00
Installing collected packages: numpy, scipy, gensim
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.2
    Uninstalling scipy-1.16.2:
      Successfully uninstalled scipy-1.16.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tsfresh 0.21.1 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed gensim-4.3.3 numpy-1.26.4 scipy-1.13.1

In [ ]:
!pip install --upgrade --force-reinstall numpy gensim

Collecting numpy
  Downloading numpy-2.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 kB 3.4 MB/s eta 0:00:00
Collecting gensim
  Using cached gensim-4.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
Collecting numpy
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting scipy<1.14.0,>=1.7.0 (from gensim)
  Using cached scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting smart-open>=1.8.1 (from gensim)
  Downloading smart_open-7.3.1-py3-none-any.whl.metadata (24 kB)
Collecting wrapt (from smart-open>=1.8.1->gensim)
  Downloading wrapt-1.17.3-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.4 kB)
Using cached gensim-4.3.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.6 MB)
Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
Using cached scipy-1.13.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.2 MB)
Downloading smart_open-7.3.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 5.0 MB/s eta 0:00:00
Downloading wrapt-1.17.3-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (88 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 kB 7.8 MB/s eta 0:00:00
Installing collected packages: wrapt, numpy, smart-open, scipy, gensim
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.17.3
    Uninstalling wrapt-1.17.3:
      Successfully uninstalled wrapt-1.17.3
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: smart-open
    Found existing installation: smart_open 7.3.1
    Uninstalling smart_open-7.3.1:
      Successfully uninstalled smart_open-7.3.1
  Attempting uninstall: scipy
    Found existing installation: scipy 1.13.1
    Uninstalling scipy-1.13.1:
      Successfully uninstalled scipy-1.13.1
  Attempting uninstall: gensim
    Found existing installation: gensim 4.3.3
    Uninstalling gensim-4.3.3:
      Successfully uninstalled gensim-4.3.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tsfresh 0.21.1 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed gensim-4.3.3 numpy-1.26.4 scipy-1.13.1 smart-open-7.3.1 wrapt-1.17.3

In [ ]:
import pandas as pd
import ast
from gensim.models import Word2Vec

In [ ]:
from google.colab import drive
import pandas as pd

# Mount Google Drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Baca CSV dari path Drive
df = pd.read_csv('/content/drive/MyDrive/Semester 7/PPW/hasil_preprocessing_berita.csv')
df.head()

,Teks Asli,Setelah Stopword Removal,Setelah Cleaning,Setelah Normalisasi,Setelah Stemming,Tokenisasi Akhir
0,alfamart kembali menggelar aksi donor darah se...,"['alfamart', 'kembali', 'menggelar', 'aksi', '...","['alfamart', 'kembali', 'menggelar', 'aksi', '...","['alfamart', 'kembali', 'menggelar', 'aksi', '...","['alfamart', 'kembali', 'gelar', 'aksi', 'dono...","['alfamart', 'kembali', 'gelar', 'aksi', 'dono..."
1,"menteri koordinator bidang hukum, ham, imigras...","['menteri', 'koordinator', 'bidang', 'hukum,',...","['menteri', 'koordinator', 'bidang', 'hukum', ...","['menteri', 'koordinator', 'bidang', 'hukum', ...","['menteri', 'koordinator', 'bidang', 'hukum', ...","['menteri', 'koordinator', 'bidang', 'hukum', ..."
2,gubernur sumatera utara (sumut) bobby nasution...,"['gubernur', 'sumatera', 'utara', '(sumut)', '...","['gubernur', 'sumatera', 'utara', 'sumut', 'bo...","['gubernur', 'sumatera', 'utara', 'sumut', 'bo...","['gubernur', 'sumatera', 'utara', 'sumut', 'bo...","['gubernur', 'sumatera', 'utara', 'sumut', 'bo..."
3,dukungan untuk plt ketua umum partai persatuan...,"['dukungan', 'plt', 'ketua', 'umum', 'partai',...","['dukungan', 'plt', 'ketua', 'umum', 'partai',...","['dukungan', 'plt', 'ketua', 'umum', 'partai',...","['dukung', 'plt', 'ketua', 'umum', 'partai', '...","['dukung', 'plt', 'ketua', 'umum', 'partai', '..."
4,bagi pengguna whoosh rute jakarta-bandung atau...,"['bagi', 'pengguna', 'whoosh', 'rute', 'jakart...","['bagi', 'pengguna', 'whoosh', 'rute', 'jakart...","['bagi', 'pengguna', 'whoosh', 'rute', 'jakart...","['bagi', 'guna', 'whoosh', 'rute', 'jakartaban...","['bagi', 'guna', 'whoosh', 'rute', 'jakartaban..."

In [ ]:
corpus = df["Tokenisasi Akhir"].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else []
).tolist()

In [ ]:
model = Word2Vec(
    sentences=corpus,
    vector_size=100,   # dimensi vektor
    window=5,          # konteks window
    min_count=2,       # kata muncul minimal 2 kali
    sg=1,              # 1=skip-gram, 0=CBOW
    workers=4
)

In [ ]:
model.save("word2vec_berita.model")

In [ ]:
# === Cek hasil ===
print("\nVektor untuk kata 'indonesia':")
print(model.wv['indonesia'][:10])

print("\nKata yang mirip dengan 'indonesia':")
print(model.wv.most_similar("indonesia", topn=5))

Vektor untuk kata 'indonesia':
[-0.11810647  0.17236815  0.00422871 -0.10403389  0.0705354  -0.35762382
  0.0828401   0.3290212  -0.1874316  -0.02492193]

Kata yang mirip dengan 'indonesia':
[('republik', 0.9742425084114075), ('selamat', 0.9715856313705444), ('prioritas', 0.9707692265510559), ('segala', 0.9696119427680969), ('atur', 0.9682633876800537)]